use crate::*;

pub static mut PLAYER01_PREVIOUS_GAMEPAD: u8 = 0;
pub static mut PLAYER01_PRESSED_THIS_FRAME: u8 = 0;

pub static mut PLAYER02_PREVIOUS_GAMEPAD: u8 = 0;
pub static mut PLAYER02_PRESSED_THIS_FRAME: u8 = 0;

pub static mut PLAYER03_PREVIOUS_GAMEPAD: u8 = 0;
pub static mut PLAYER03_PRESSED_THIS_FRAME: u8 = 0;

pub static mut PLAYER04_PREVIOUS_GAMEPAD: u8 = 0;
pub static mut PLAYER04_PRESSED_THIS_FRAME: u8 = 0;

pub unsafe fn gamepad_update()
{
    PLAYER01_PRESSED_THIS_FRAME = *GAMEPAD1 & (*GAMEPAD1 ^ PLAYER01_PREVIOUS_GAMEPAD);
    PLAYER01_PREVIOUS_GAMEPAD = *GAMEPAD1;

    PLAYER02_PRESSED_THIS_FRAME = *GAMEPAD2 & (*GAMEPAD2 ^ PLAYER02_PREVIOUS_GAMEPAD);
    PLAYER02_PREVIOUS_GAMEPAD = *GAMEPAD2;

    PLAYER03_PRESSED_THIS_FRAME = *GAMEPAD3 & (*GAMEPAD3 ^ PLAYER03_PREVIOUS_GAMEPAD);
    PLAYER03_PREVIOUS_GAMEPAD = *GAMEPAD3;

    PLAYER04_PRESSED_THIS_FRAME = *GAMEPAD4 & (*GAMEPAD4 ^ PLAYER04_PREVIOUS_GAMEPAD);
    PLAYER04_PREVIOUS_GAMEPAD = *GAMEPAD4;
}
